# Generated by Django 5.0.3 on 2024-05-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0004_busrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busrequest',
            name='user',
        ),
    ]
